# Generated by Django 2.1 on 2018-09-20 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, null=True, verbose_name='Nombre')),
                ('tipo_resultado', models.CharField(choices=[('numb', 'Numérico'), ('bool', 'Post-Negt')], max_length=30, verbose_name='Tipo de resultado')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.UnidadMedida')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis_nombre', models.CharField(max_length=64, null=True, verbose_name='Nombre')),
                ('tipo_resultado', models.CharField(max_length=30, verbose_name='Tipo de resultado')),
                ('valor_numerico', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('analisis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis_clinicos.Analisis')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
