# Generated by Django 2.1 on 2018-09-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_clinicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Resultado'),
        ),
    ]
